env:
  FORCE_COLOR: 1
  GIT_TERMINAL_PROMPT: 0

steps:
  # We disable earthly's caching because otherwise we'd be at risk of publishing
  # whatever protocol version Earthly has in its cache, instead of reinstalling
  # the latest version from npm.
  - command: >
      earthly --no-cache +build &&
      aws s3 sync protocol s3://recordreplay-website/protocol/ &&
      aws cloudfront create-invalidation --distribution-id E3U30CHVUQVFAF --paths "/protocol/*"
    agents:
      - "earthly=true"
      - "deploy=true"
